[
{"lat":"48.858160","lng":"2.341719","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Paris","place":"http://static.flickr.com/38/105513078_f73bb0fa12_s.jpg"},
{"lat":"40.414871","lng":"-3.704263","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Madrid","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"37.176979","lng":"-3.597709","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Granada","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"38.721794","lng":"-9.137888","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Lisbon","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"41.384722","lng":"2.170134","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Barcelona","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"51.489474","lng":"-0.138771","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"London","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"50.847074","lng":"4.358219","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Bruxelles","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"52.371396","lng":"4.895356","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Amsterdam","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"46.946109","lng":"7.450226","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Bern","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"50.113694","lng":"8.678756","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Frankfurt am Main","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"48.132297","lng":"11.578162","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"München","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"45.440445","lng":"12.305751","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Comune di Venezia","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"43.762870","lng":"11.256117","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Firenze","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"41.892694","lng":"12.498052","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Rome","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"52.515309","lng":"13.408515","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Berlin","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"50.070542","lng":"14.438960","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Praha","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"48.213227","lng":"16.381295","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Wien","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"47.493567","lng":"19.039660","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Budapest","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"37.985234","lng":"23.729172","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Athens","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"52.223748","lng":"21.002516","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Warszawa","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"41.008485","lng":"28.974574","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"İstanbul","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"59.330791","lng":"18.067569","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Stockholm","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"60.158366","lng":"24.962335","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Helsinki","place":"http://localhost/flamingogo/user/planner/plannerstep1.jsp"},
{"lat":"55.752688","lng":"37.598175","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Москва","place":""},
{"lat":"","lng":"","icon":"","cont":""}
]

