[
{"lat":"48.858160","lng":"2.341719","icon":"http://www.stubbyplanner.com/img_v8/selectcityICON_red.png","cont":"Paris","place":"http://static.flickr.com/38/105513078_f73bb0fa12_s.jpg"},
{"lat":"","lng":"","icon":"","cont":""},
{"lat":"","lng":"","icon":"","cont":""},
{"lat":"","lng":"","icon":"","cont":""},
{"lat":"","lng":"","icon":"","cont":""},
{"lat":"","lng":"","icon":"","cont":""},
{"lat":"","lng":"","icon":"","cont":""},
{"lat":"","lng":"","icon":"","cont":""},
]